### ISSUE TITLE
Rebuild lj.com

### ISSUE THREAD

**Issue by johnsiwicki** [bs-production/front-end-guidelines#64]
Path: /graphics/Dennis/Web/LarryJanesky.com/LarryJanesky-Website-Main.psd

**Comment by johnsiwicki** [comment]
### Todos
- [ ] Need a CORS header for the WP API For All Sites
- [ ] Check with Dennis for any store design
- [ ] Mobile Designs
- [ ] Homepage TD Scroll and Timeline
